# Magnum CI (MIT License) configuration file for Subtitles WordPress Plugin
# @link https://magnum-ci.com/

# For use with the Subtitles WordPress Plugin
# @link https://github.com/philiparthurmoore/Subtitles

